- name: Check Gradle project
  run: |
    pwd
    echo "=== ROOT ==="
    ls -la
    echo "=== SETTINGS ==="
    cat settings.gradle
    echo "=== APP ==="
    ls -la app
    echo "=== APP GRADLE ==="
    cat app/build.gradle

- name: Show Gradle tasks
  run: gradle tasks --all
